// @ts-check
// One autogenerated sidebar; folder order and labels come from each folder's _category_.json.
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
